version: "3.8"

networks:
  multidc-network:
    name: multidc-network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [multidc-network]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # optional, but fine
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # ðŸ‘‡ ONLY ONE LISTENER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks: [multidc-network]

  kafka-connect:
    image: debezium/connect:2.5
    container_name: kafka-connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /kafka/connect/plugins
    volumes:
      - ./plugins/debezium-connector-mongodb:/kafka/connect/plugins/debezium-connector-mongodb:ro
      - ./plugins/mongodb-kafka-connect-mongodb:/kafka/connect/plugins/mongodb-kafka-connect-mongodb:ro
    networks:
      - multidc-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
      - kafka-connect
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
    networks:
      - multidc-network

  mongodb-de1:
    image: mongo:7.0
    container_name: mongodb-de1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - multidc-network

  mongodb-br1:
    image: mongo:7.0
    container_name: mongodb-br1
    command: ["--replSet", "rs1", "--bind_ip_all"]
    networks:
      - multidc-network

  mongodb-sg1:
    image: mongo:7.0
    container_name: mongodb-sg1
    command: ["--replSet", "rs2", "--bind_ip_all"]
    networks:
      - multidc-network

  mongodb-readdb:
    image: mongo:7.0
    container_name: mongodb-readdb
    command: ["--replSet", "rs3", "--bind_ip_all"]
    networks:
      - multidc-network
